### ISSUE TITLE
Add ability to use query counts on AberOWL

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.datasources#10]
Sample query, now available: 

http://vfbdev.inf.ed.ac.uk/aberowl/api/runQuery.groovy?type=subeq&count=true&query=%3Chttp://purl.obolibrary.org/obo/BFO_0000050%3E%20some%20%3Chttp://purl.obolibrary.org/obo/FBbt_00003624%3E&ontology=VFB

‘count=true'

returns 
```
{"result":1467,"time":546}
```

**Comment by Robbie1977** [comment]
Changed to a tabled value to match the expected results:
```{"result":{"count":1467},"time":629}```

**Comment by tarelli** [comment]
From Robb: looks like this is not a problem in the end.
